### ISSUE TITLE
style: Tests fail to compile on Linux

### ISSUE THREAD

**Issue by ignatenkobrain** [TimonPost/crossterm#103] opened 2019-03-15 05:30 UTC
```rust
error[E0601]: `main` function not found in crate `style`
  |
  = note: consider adding a `main` function to `examples/style.rs`
```

**Comment by TimonPost** [comment] 2019-03-15 11:46
Right, I see the problem, it is caused by an update I did some time ago, let's close this issue and make a single one.

**Comment by TimonPost** [comment] 2019-04-04 17:36
Closing in favor of #112

**Closed by TimonPost** 2019-04-04 17:36 UTC
