### ISSUE TITLE
Tests fail to compile

### ISSUE THREAD

**Issue by ignatenkobrain** [TimonPost/crossterm#105] opened 2019-03-15 05:42 UTC
```rust
running 8 tests
test src/crossterm.rs - crossterm::Crossterm::color (line 94) ... FAILED
test src/crossterm.rs - crossterm::Crossterm::terminal (line 80) ... FAILED
test src/crossterm.rs - crossterm::Crossterm::cursor (line 52) ... FAILED
test src/crossterm.rs - crossterm::Crossterm::input (line 66) ... FAILED
test src/crossterm.rs - crossterm::Crossterm (line 11) ... FAILED
test src/crossterm.rs - crossterm::Crossterm::paint (line 136) ... FAILED
test src/crossterm.rs - crossterm::Crossterm (line 19) ... FAILED
test src/crossterm.rs - crossterm::Crossterm::style (line 109) ... FAILED

failures:

---- src/crossterm.rs - crossterm::Crossterm::color (line 94) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:95:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm::color (line 94)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::terminal (line 80) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:81:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm::terminal (line 80)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::cursor (line 52) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:53:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm::cursor (line 52)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::input (line 66) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:67:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm::input (line 66)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- src/crossterm.rs - crossterm::Crossterm (line 11) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:12:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

thread 'src/crossterm.rs - crossterm::Crossterm (line 11)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::paint (line 136) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:138:11
  |
4 |     .with(Color::Blue)
  |           ^^^^^ use of undeclared type or module `Color`

error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:139:9
  |
5 |     .on(Color::Black)
  |         ^^^^^ use of undeclared type or module `Color`

error[E0425]: cannot find function `style` in this scope
 --> src/crossterm.rs:137:1
  |
3 | style("Some colored text")
  | ^^^^^ not found in this scope

error[E0425]: cannot find value `screen` in this scope
 --> src/crossterm.rs:140:13
  |
6 |     .paint(&screen);
  |             ^^^^^^ not found in this scope

thread 'src/crossterm.rs - crossterm::Crossterm::paint (line 136)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm (line 19) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Screen`
 --> src/crossterm.rs:20:19
  |
4 | let main_screen = Screen::default();
  |                   ^^^^^^ use of undeclared type or module `Screen`

error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:24:20
  |
8 |    let crossterm = Crossterm::new(&alternate_screen.screen);
  |                    ^^^^^^^^^ use of undeclared type or module `Crossterm`

error[E0425]: cannot find value `alternate_screen` in this scope
 --> src/crossterm.rs:24:36
  |
8 |    let crossterm = Crossterm::new(&alternate_screen.screen);
  |                                    ^^^^^^^^^^^^^^^^ help: a local variable with a similar name exists: `alternate_srceen`

thread 'src/crossterm.rs - crossterm::Crossterm (line 19)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13

---- src/crossterm.rs - crossterm::Crossterm::style (line 109) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `Crossterm`
 --> src/crossterm.rs:110:17
  |
4 | let crossterm = Crossterm::new();
  |                 ^^^^^^^^^ use of undeclared type or module `Crossterm`

error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:114:11
  |
8 |     .with(Color::Blue)
  |           ^^^^^ use of undeclared type or module `Color`

error[E0433]: failed to resolve: use of undeclared type or module `Color`
 --> src/crossterm.rs:115:9
  |
9 |     .on(Color::Black);
  |         ^^^^^ use of undeclared type or module `Color`

thread 'src/crossterm.rs - crossterm::Crossterm::style (line 109)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:321:13
```

**Comment by TimonPost** [comment] 2019-03-15 11:45
Right, I see the problem, it is caused by an update I did some time ago, let's close this issue and make a single one.

**Comment by TimonPost** [comment] 2019-04-04 17:35
closing in favor of: #112

**Closed by TimonPost** 2019-04-04 17:35 UTC
