### ISSUE TITLE
terminal: Tests fail to compile on Linux

### ISSUE THREAD

**Issue by ignatenkobrain** [TimonPost/crossterm#104] opened 2019-03-15 05:33 UTC
```rust
error[E0432]: unresolved import `super::WinApiTerminal`
 --> src/terminal/test.rs:1:38
  |
1 | use super::{AnsiTerminal, ITerminal, WinApiTerminal};
  |                                      ^^^^^^^^^^^^^^ no `WinApiTerminal` in `terminal`. Did you mean to use `AnsiTerminal`?
```

**Comment by TimonPost** [comment] 2019-03-15 11:45
Right, I see the problem, it is caused by an update I did some time ago, let's close this issue and make a single one.

**Comment by TimonPost** [comment] 2019-04-04 17:35
closing in favor of: #112

**Closed by TimonPost** 2019-04-04 17:35 UTC
