### ISSUE TITLE
Snake example does not compile on Windows

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [TimonPost/crossterm#109] opened 2019-03-27 14:11 UTC
To reproduce, follow the instructions in [examples/program_examples/README.md](https://github.com/TimonPost/crossterm/blob/master/examples/program_examples/README.md). Specifically,
```
git clone git@github.com:TimonPost/crossterm.git
cd crossterm/examples/program_examples/snake
cargo run
```

I got this:
```
error: current package believes it's in a workspace when it's not:
current:   redacted\crossterm\examples\program_examples\snake\Cargo.toml
workspace: redacted\crossterm\Cargo.toml
```

Okay, doing as suggested. Now `cargo run` produces the following error:
```
error[E0432]: unresolved import `crossterm::ColorType`
 --> examples\program_examples\snake\src\map.rs:5:19
  |
5 |     style, Color, ColorType, Crossterm, ObjectStyle, Screen, StyledObject, TerminalCursor,
  |                   ^^^^^^^^^ no `ColorType` in the root. Did you mean to use `Colorize`?
```

**Comment by TimonPost** [comment] 2019-03-27 17:01
Ah thanks for saying that, it was caused by the last updated. It will be fixed.

**Comment by TimonPost** [comment] 2019-04-04 17:20
fixed

**Closed by TimonPost** 2019-04-04 17:20 UTC
